# Generated by Django 2.2.3 on 2019-08-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employeeID',
            new_name='email1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
